# Generated by Django 5.2.5 on 2025-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailing_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=9,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingtry",
            name="date_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время попытки"
            ),
        ),
        migrations.AlterField(
            model_name="mailingtry",
            name="response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ответ почтового сервера"
            ),
        ),
        migrations.AlterField(
            model_name="mailingtry",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                max_length=10,
                verbose_name="Статус попытки",
            ),
        ),
    ]
