# Generated by Django 5.2.5 on 2025-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_mailing_status_alter_mailingtry_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Ф.И.О."),
        ),
    ]
