# Generated by Django 5.2.5 on 2025-08-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_recipient_email_alter_recipient_full_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["sending_start", "sending_end"],
                "permissions": [("can_stop_mailing", "Can stop mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
